#!/bin/sh

# Give a battery name (e.g. BAT0) as an argument.

capacity=$(cat /sys/class/power_supply/"$1"/capacity) || exit
status=$(cat /sys/class/power_supply/"$1"/status)

if [ "$capacity" -ge 80 ]; then
	color="#FFFFFF"
elif [ "$capacity" -ge 60 ]; then
	color="#FFFFFF"
elif [ "$capacity" -ge 40 ]; then
	color="#FFFFFF"
elif [ "$capacity" -ge 30 ]; then
	color="#FFFFFF"
elif [ "$capacity" -ge 20 ]; then
	color="#FFFFFF"
else
	color="#FF0000"
fi

[ "$status" = "Charging" ] && color="#FFF"

printf "<span color='%s'>%s %s</span>" "$color" "$(echo "$status" | sed -e "s/,//g;s/Discharging/;s/Charging//;s/Unknown/;s/Full/;s/ 0*/ /g;s/ :/ /g")" "$(echo "$capacity" | sed -e 's/$/%/')"
